jatos.multiNode = true
jatos.groupMessageAckTimeout = 3 seconds
jatos.logs.appender = "ASYNCSTDOUT"
jatos.logs.level.batch = DEBUG
jatos.logs.level.group = DEBUG

pekko.actor.provider = cluster
# Shared by both fixed seeds and scalable replicas. Each has its own HOSTNAME.
pekko.remote.artery.canonical.hostname = ${HOSTNAME}
pekko.remote.artery.canonical.port = 25520
pekko.cluster.seed-nodes = [
  "pekko://application@jatos-seed-1:25520",
  "pekko://application@jatos-seed-2:25520"
]
pekko.cluster.downing-provider-class = "org.apache.pekko.cluster.sbr.SplitBrainResolverProvider"
