include "application.conf"

jatos.multiNode = true
jatos.groupMessageAckTimeout = 3 seconds
jatos.logs.appender = "ASYNCSTDOUT"

pekko.actor.provider = cluster
# Docker supplies a unique HOSTNAME for each replica of the scalable service.
pekko.remote.artery.canonical.hostname = ${HOSTNAME}
pekko.remote.artery.canonical.port = 25520
pekko.cluster.seed-nodes = [
  "pekko://application@jatos-seed:25520"
]
pekko.cluster.downing-provider-class = "org.apache.pekko.cluster.sbr.SplitBrainResolverProvider"
